### ISSUE TITLE
Could you release the current version to CPAN?

### ISSUE THREAD

**Issue by Htbaa** [majensen/dbd-neo4p#2]
Hi,

I recently moved servers and after installing my project I installed the version from CPAN and not the one from here. My pull request #1 fixed an issue where the temp files didn't clean up. So I just noticed my docker container running my app had 18GB of temp files resulting from DBD::Neo4p.

I would really appreciate it if you could do a new release to CPAN.

**Comment by Htbaa** [comment]
Actually, the same goes for REST::Neo4p.

**Comment by majensen** [comment]
REST::Neo4p 0.3020 and DBD::Neo4p 0.1004
thanks
